<?php

namespace CoursBundle\Repository;

/**
 * HistoricRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricRepository extends \Doctrine\ORM\EntityRepository
{
    public function historicsUser($user)
    {
        $qb = $this->createQueryBuilder('h')
            ->select('l.id')->distinct()
            ->andWhere('u.id = :user')
            ->setParameter('user', $user)
            ->join('h.lesson', 'l')
            ->join('h.user', 'u');
        return $qb->getQuery()->getResult();
    }
}
